<a href="https://colab.research.google.com/github/LukaLjevar/projektna_statistika/blob/main/Temp_MN_se_enkrat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [242]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats import t

df = pd.read_csv('Temp_MN.csv')
n = df.shape[0]
print(n)


1115


In [243]:
#Poračunamo sinuse dni s predfaktorjem in jih seštejemo

vsota_sinusov=np.sin(2*np.pi*df["DAN"]/365.25).sum()

# Print the result
print("Vsota_sinusov:", vsota_sinusov)

Vsota_sinusov: 87.11770195335194


In [244]:
#Poračunamo kosinuse dni s predfaktorjem in jih seštejemo

vsota_kosinusov=np.cos(2*np.pi*df["DAN"]/365.25).sum()

# Print the result
print("Vsota_kosinusov:", vsota_kosinusov)

Vsota_kosinusov: 94.95872171546173


In [245]:
#Poračunamo kvadrate sinusov dni s predfaktorjem in jih seštejemo

vsota_kvadratov_sinusov=(np.square(np.sin(2*np.pi*df["DAN"]/365.25))).sum()

# Print the result
print("Vsota_kvadratov_sinusov:", vsota_kvadratov_sinusov)

Vsota_kvadratov_sinusov: 554.6892645378354


In [246]:
#Poračunamo kvadrate kosinusov dni s predfaktorjem in jih seštejemo

vsota_kvadratov_kosinusov=(np.square(np.cos(2*np.pi*df["DAN"]/365.25))).sum()

# Print the result
print("Vsota_kvadratov_kosinusov:", vsota_kvadratov_kosinusov)

Vsota_kvadratov_kosinusov: 560.3107354621646


In [247]:
#Poračunamo SIN*COS dni s predfaktorjem in jih seštejemo

vsota_SINCOS=np.sin(4*np.pi*df["DAN"]/365.25).sum()/2

# Print the result
print("Vsota_SINCOS:", vsota_SINCOS)

Vsota_SINCOS: 31.675359696895132


In [248]:
XTX = np.matrix([[n, vsota_sinusov, vsota_kosinusov], [vsota_sinusov, vsota_kvadratov_sinusov, vsota_SINCOS], [vsota_kosinusov, vsota_SINCOS, vsota_kvadratov_kosinusov]])
print(XTX)

[[1115.           87.11770195   94.95872172]
 [  87.11770195  554.68926454   31.6753597 ]
 [  94.95872172   31.6753597   560.31073546]]


In [249]:
inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

[[ 9.20115835e-04 -1.36044882e-04 -1.48245871e-04]
 [-1.36044882e-04  1.82876499e-03 -8.03271076e-05]
 [-1.48245871e-04 -8.03271076e-05  1.81438899e-03]]


In [250]:
test = np.linalg.inv(inv_XTX)
print(test)

[[1115.           87.11770195   94.95872172]
 [  87.11770195  554.68926454   31.6753597 ]
 [  94.95872172   31.6753597   560.31073546]]


In [251]:
Y = df["TEMP"].to_numpy()

print("Y:", Y)

Y: [28.07 26.65 26.49 ... 15.53 12.18  8.26]


In [252]:
#Še matrika X
dan =df["DAN"]
X = np.column_stack((
    np.ones(len(dan)),
    np.sin(2*np.pi*dan/365.25),
    np.cos(2*np.pi*dan/365.25)
))

print("Constructed matrix:")
print(matrix)

Constructed matrix:
[[ 1.          0.84147098  0.54030231]
 [ 1.          0.90929743 -0.41614684]
 [ 1.          0.14112001 -0.9899925 ]
 ...
 [ 1.         -0.97265108 -0.23227114]
 [ 1.         -0.72097505  0.69296102]
 [ 1.          0.19356212  0.98108802]]


In [253]:
XT = np.matrix_transpose(X)
print(XT)

[[ 1.          1.          1.         ...  1.          1.
   1.        ]
 [ 0.01720158  0.03439806  0.05158437 ...  0.99639502  0.99478831
   0.99288721]
 [ 0.99985204  0.99940821  0.99866864 ... -0.08483488 -0.10196189
  -0.11905873]]


In [254]:
beta =np.matmul(np.matmul(inv_XTX, XT), Y)
print(beta)

[[12.29655083  7.29833196 14.36784201]]
