<a href="https://colab.research.google.com/github/LukaLjevar/projektna_statistika/blob/main/Temp_MN_se_enkrat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [119]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats import t

df = pd.read_csv('Temp_MN.csv')
n = df.shape[0]
print(n)


1115


In [120]:
#Poračunamo sinuse dni s predfaktorjem in jih seštejemo

vsota_sinusov=np.sin(2*np.pi*df["DAN"]/365.25).sum()

# Print the result
print("Vsota_sinusov:", vsota_sinusov)

Vsota_sinusov: 87.11770195335194


In [121]:
#Poračunamo kosinuse dni s predfaktorjem in jih seštejemo

vsota_kosinusov=np.cos(2*np.pi*df["DAN"]/365.25).sum()

# Print the result
print("Vsota_kosinusov:", vsota_kosinusov)

Vsota_kosinusov: 94.95872171546173


In [122]:
#Poračunamo kvadrate sinusov dni s predfaktorjem in jih seštejemo

vsota_kvadratov_sinusov=(np.square(np.sin(2*np.pi*df["DAN"]/365.25))).sum()

# Print the result
print("Vsota_kvadratov_sinusov:", vsota_kvadratov_sinusov)

Vsota_kvadratov_sinusov: 554.6892645378354


In [123]:
#Poračunamo kvadrate kosinusov dni s predfaktorjem in jih seštejemo

vsota_kvadratov_kosinusov=(np.square(np.cos(2*np.pi*df["DAN"]/365.25))).sum()

# Print the result
print("Vsota_kvadratov_kosinusov:", vsota_kvadratov_kosinusov)

Vsota_kvadratov_kosinusov: 560.3107354621646


In [124]:
#Poračunamo SIN*COS dni s predfaktorjem in jih seštejemo

vsota_SINCOS=np.sin(4*np.pi*df["DAN"]/365.25).sum()/2

# Print the result
print("Vsota_SINCOS:", vsota_SINCOS)

Vsota_SINCOS: 31.675359696895132


In [125]:
XTX = np.matrix([[n, vsota_sinusov, vsota_kosinusov], [vsota_sinusov, vsota_kvadratov_sinusov, vsota_SINCOS], [vsota_kosinusov, vsota_SINCOS, vsota_kvadratov_kosinusov]])
print(XTX)

[[1115.           87.11770195   94.95872172]
 [  87.11770195  554.68926454   31.6753597 ]
 [  94.95872172   31.6753597   560.31073546]]


In [126]:
inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

[[ 9.20115835e-04 -1.36044882e-04 -1.48245871e-04]
 [-1.36044882e-04  1.82876499e-03 -8.03271076e-05]
 [-1.48245871e-04 -8.03271076e-05  1.81438899e-03]]


In [127]:
test = np.linalg.inv(inv_XTX)
print(test)

[[1115.           87.11770195   94.95872172]
 [  87.11770195  554.68926454   31.6753597 ]
 [  94.95872172   31.6753597   560.31073546]]


In [128]:
Y = df["TEMP"].to_numpy()

print("Y:", Y)

Y: [28.07 26.65 26.49 ... 15.53 12.18  8.26]


In [129]:
#Še matrika X
dan =df["DAN"]
X = np.column_stack((
    np.ones(len(dan)),
    np.sin(2*np.pi*dan/365.25),
    np.cos(2*np.pi*dan/365.25)
))

print("Constructed matrix:")
print(X)

Constructed matrix:
[[ 1.          0.01720158  0.99985204]
 [ 1.          0.03439806  0.99940821]
 [ 1.          0.05158437  0.99866864]
 ...
 [ 1.          0.99639502 -0.08483488]
 [ 1.          0.99478831 -0.10196189]
 [ 1.          0.99288721 -0.11905873]]


In [130]:
XT = np.matrix_transpose(X)
print(XT)

[[ 1.          1.          1.         ...  1.          1.
   1.        ]
 [ 0.01720158  0.03439806  0.05158437 ...  0.99639502  0.99478831
   0.99288721]
 [ 0.99985204  0.99940821  0.99866864 ... -0.08483488 -0.10196189
  -0.11905873]]


In [131]:
beta =np.matmul(np.matmul(inv_XTX, XT), Y)
print(beta)

[[12.29655083  7.29833196 14.36784201]]


In [132]:
sigm = np.sqrt(np.linalg.norm(Y-np.matmul(X, np.matrix_transpose(beta)))/1112)
print(sigm)

4.1657085636967475


In [133]:
c = [[1],[np.sin(2*np.pi*1195/365.25)],[np.cos(2*np.pi*1195/365.25)]]
print(c)

[[1], [np.float64(0.9906923101615611)], [np.float64(-0.13612033862266606)]]


In [134]:
A=np.matmul(np.matmul(np.matrix_transpose(c),inv_XTX),c)
print(A)

[[0.00254108]]


In [135]:
Aa =float(np.ravel(A).item())
print(Aa)

0.0025410805373233974


In [136]:
sep = sigm * np.sqrt(1+Aa)
print(sep)

4.170997906145048


In [137]:
delta = 1.96*sep
print(delta)

8.175155896044293


In [138]:
pred = float(np.ravel(np.matmul(np.matrix_transpose(c), np.matrix_transpose(beta))).item())
print(pred)

17.571196665989707


In [139]:
spodnja = pred - delta
zgornja = pred + delta
print("spodnja:", spodnja)
print("zgornja:", zgornja)

spodnja: 9.396040769945413
zgornja: 25.746352562033998
