<a href="https://colab.research.google.com/github/LukaLjevar/projektna_statistika/blob/main/Temp_MN_se_enkrat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats import t

df = pd.read_csv('Temp_MN.csv')
n = df.shape[0]
print(n)


1115


In [136]:
#Poračunamo sinuse dni s predfaktorjem in jih seštejemo

vsota_sinusov=np.sin(2*np.pi*df["DAN"]/365.25).sum()

# Print the result
print("Vsota_sinusov:", vsota_sinusov)

Vsota_sinusov: 87.11770195335194


In [137]:
#Poračunamo kosinuse dni s predfaktorjem in jih seštejemo

vsota_kosinusov=np.cos(2*np.pi*df["DAN"]/365.25).sum()

# Print the result
print("Vsota_kosinusov:", vsota_kosinusov)

Vsota_kosinusov: 94.95872171546173


In [138]:
#Poračunamo kvadrate sinusov dni s predfaktorjem in jih seštejemo

vsota_kvadratov_sinusov=(np.square(np.sin(2*np.pi*df["DAN"]/365.25))).sum()

# Print the result
print("Vsota_kvadratov_sinusov:", vsota_kvadratov_sinusov)

Vsota_kvadratov_sinusov: 554.6892645378354


In [139]:
#Poračunamo kvadrate kosinusov dni s predfaktorjem in jih seštejemo

vsota_kvadratov_kosinusov=(np.square(np.cos(2*np.pi*df["DAN"]/365.25))).sum()

# Print the result
print("Vsota_kvadratov_kosinusov:", vsota_kvadratov_kosinusov)

Vsota_kvadratov_kosinusov: 560.3107354621646


In [140]:
#Poračunamo SIN*COS dni s predfaktorjem in jih seštejemo

vsota_SINCOS=np.sin(4*np.pi*df["DAN"]/365.25).sum()/2

# Print the result
print("Vsota_SINCOS:", vsota_SINCOS)

Vsota_SINCOS: 31.675359696895132


In [141]:
XTX = np.matrix([[n, vsota_sinusov, vsota_kosinusov], [vsota_sinusov, vsota_kvadratov_sinusov, vsota_SINCOS], [vsota_kosinusov, vsota_SINCOS, vsota_kvadratov_kosinusov]])
print(XTX)

[[1115.           87.11770195   94.95872172]
 [  87.11770195  554.68926454   31.6753597 ]
 [  94.95872172   31.6753597   560.31073546]]


In [142]:
inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

[[ 9.20115835e-04 -1.36044882e-04 -1.48245871e-04]
 [-1.36044882e-04  1.82876499e-03 -8.03271076e-05]
 [-1.48245871e-04 -8.03271076e-05  1.81438899e-03]]


In [143]:
test = np.linalg.inv(inv_XTX)
print(test)

[[1115.           87.11770195   94.95872172]
 [  87.11770195  554.68926454   31.6753597 ]
 [  94.95872172   31.6753597   560.31073546]]


In [144]:
Y = df["DAN"].to_numpy()

print("Y:", Y)

Y: [   1    2    3 ... 1192 1193 1194]
